toolforge/paws

singleuser/Dockerfile
singleuser/user-config.py

So the default will always be autogenerated, but the custom ones can be persisted.

Allow customizing user-config.py

---

singleuser/user-config.py

Since pwb issues a warning otherwise

Cleanup unused vars

---

toolinfo.json

Complete step #1 of adding a new project to Tools Directory[0]. Step #2
- 3 will point to the GitHub repo once this is merged.
[0] https://tools.wmflabs.org/hay/directory/?search=paws#addtool

Add PAWS to Tools Directory

---

paws/values.yaml

Web admin interface access may help with idle containers until we have the culler fixed.

add chicocvenancio and zhuyifei1999 as admins

---

paws/requirements.yaml

Fixes https://phabricator.wikimedia.org/T175202

upgrade jupyterhub version

---

images/singleuser/banner

Point to #wikimedia-cloud instead of #pywikibot

change banner freenode channel for help

---

paws/values.yaml

Check `/public/dumps/incr` for dumps nfs mount, tested in paws-beta

Check `/public/dumps/incr` for dumps nfs mount

---

paws/values.yaml

See [T218600](https://phabricator.wikimedia.org/T218600)

values.yaml: add  to pywikibot update command to allow for pull failure

---

paws/values.yaml

This is so convoluted :(
CC: #33
Bug: T217908
Bug: T252290

values.yaml: Update pywikibot at pod launch time

---

README.md

In order to help people contribute and establish code review practices,
add a note on where and how to do these things now that the repo is mirrored
and the master branch is protected.
Bug: T255635

docs: update the README.md with a note about contribution and PRs

---

.travis.yml
images/nbserve/nginx.py
images/paws-hub/cull_idle_servers.py
images/renderer/renderer.py
images/singleuser/user-config.py
images/singleuser/user-fixes.py
paws/Chart.yaml
tox.ini
travis-script.bash

This is the second version of this. This will run the python lint, helm lint, kubernetes validation in parallel and does the docker build only if that succeeds. Besides that, it will only run deploy if **all** of that succeeds and we are on "master" branch. 
This obviously does not call the deploy because that's still a bit broken, but it should work. Test run here: https://travis-ci.com/github/toolforge/paws/builds/179500608
Also, my only concern on this change is here: https://github.com/toolforge/paws/blob/ci-improvements/images/singleuser/user-config.py#L6-L10  That's necessary for linting to succeed, but I'd like to test it with pywikibot to make sure it doesn't care about the hack, if a kind reviewer has a good setup for testing that first, please do!

Ci improvements

---

paws/values.yaml

I think its a good place to have an announcement about the replicas. The wording can probably be improved. (And I haven't tested this locally yet)

Change announcement banner to inform of new replicas

---

images/singleuser/Dockerfile
images/singleuser/requirements.txt

Fixes https://phabricator.wikimedia.org/T193341

Add SPARQL Kernel

---

images/singleuser/install-extensions
images/singleuser/requirements.txt

- holoviews (panel), dash (plotly) and streamlit are similar to
voila, in helping build 'dashboard' style interfaces that can
be used without needing to write code.
- flask & fastapi can be used to develop and build servers that
provide a similar experience as a dashboard, but with more work

Add visualization + app building packages

---

images/singleuser/Dockerfile

see https://github.com/wikimedia/pywikibot/blob/a2b9ddaee746ad288d1b21e6b30d0b9ce035a1e9/pywikibot/config.py#L63

Update pywikibot home env variable name

---

ingress/values.yaml

This should be paired with an upgrade of the ingress-nginx chart to
4.0.6.

Upgrade ingress-nginx to 1.0.4

---

images/singleuser/Dockerfile
paws/values.yaml

Closes: https://phabricator.wikimedia.org/T298183

images/singleuser: Bump OpenRefine to 3.5.1

---

manifests/psp.yaml

This is applied to the cluster, committing as documentation.

Change psp to allow minesweeper

---

images/singleuser/Dockerfile
paws/values.yaml

Would fix the issue for T296385, though would we be opening the door to adding too many random libs?

dep for pyaudio T296385

---

paws/values.yaml

https://phabricator.wikimedia.org/T303332

banner update for move to JupyterLab

---

images/singleuser/Dockerfile
paws/values.yaml

Not sure if we would want to announce this some before sending it out. The interface would be, suddenly, different.
https://phabricator.wikimedia.org/T295043

move to jupyterlab

---

images/renderer/README.md
images/renderer/requirements.txt
paws/values.yaml

T308862: Fix version of nbvconvert

---

.github/workflows/lint.yaml
.github/workflows/update-container-tags.yaml
README.md

global: move to main as the default branch

---

ingress/values.yaml

This needs to be combined with upgrading the ingress-nginx helm chart to
4.2.3.

Upgrade ingress-nginx to 1.3.0

---

paws/Chart.yaml

Upgrade jupyterhub chart

---

.github/workflows/notification.yaml

Post to phabricator on PR close

---

images/singleuser/Dockerfile
paws/values.yaml

Upgrade IRkernel

---

images/singleuser/Dockerfile
paws/values.yaml

Upgrade jupyterlab

---

images/singleuser/Dockerfile
paws/values.yaml

openrefine bump

---

images/singleuser/Dockerfile
paws/values.yaml

jupyterhub to 3.0

---

images/nbserve/nginx.py
paws/values.yaml

Adding commentary regarding nginx rewrites

---

paws/templates/localdev.yaml
paws/templates/public.yaml
paws/values.yaml

Delete all of your paws volumes before testing.
Bug: T324265

update minikube to work with prod changes

---

images/nbserve/nginx.py
paws/values.yaml

Do not load index files automatically

---

images/paws-hub/Dockerfile
paws/Chart.yaml
paws/values.yaml

Upgrade to jupyterhub chart 2.0.0

---

paws/values.yaml

update admin users

---

paws/templates/frontpage.yaml
paws/templates/legacy.yaml
paws/templates/public.yaml
paws/values.yaml

ingress options for ingress-nginx

---

.gitattributes
.yamllint.conf
paws/codfw1dev-secrets.yaml
paws/codfw1dev.yaml

setup dns for paws-dev

---

paws/codfw1dev.yaml
paws/production.yaml
paws/templates/public.yaml
paws/values.yaml

Add paws-dev nfs variable information

---

paws/codfw1dev.yaml
paws/production.yaml
paws/templates/public.yaml
paws/values.yaml

Variables for nbserve and renderer resource requests

---

paws/templates/public.yaml

cpu limit for renderer

---

paws/codfw1dev.yaml
paws/production.yaml

remove missed dbProxy configs

---

paws/values.yaml

remove automatic updating in pwb

---

paws/production.yaml
paws/values.yaml

Update and mapped src 1 to 1001and src2 to 1002
Bug:T326675

Set 1 to = 1 for nfs names in PAWS 

---

images/singleuser/Dockerfile
images/singleuser/install-extensions
images/singleuser/requirements.txt
paws/values.yaml

removing favicon code to unblock

---

images/singleuser/Dockerfile
paws/values.yaml

OpenRefine version bump

---

images/singleuser/Dockerfile
paws/values.yaml

This reverts commit c3450668212846ef1430941d17f9890274247a4d.

Revert "upgrade jupyterlab jupyterhub notebook (#244)"

---

images/singleuser/Dockerfile
paws/values.yaml

upgrade jupyterhub

---

README.md
paws/values.yaml
terraform/123.tf
terraform/vars.tf

Bug: T340657
Codfw1dev cannot deploy magnum clusters, so this has not been verified to fully work there, but the code is useful for eqiad1 so merging before that.

Deploy to codfw1dev with terraform

---

paws/values.yaml
terraform/123_5.tf
terraform/vars.tf

terraform in eqiad1

---

terraform/vars.tf

Update variable for TF in codfw

---

tests/helm-lint/Dockerfile

Helm container version bump

---

terraform/vars.tf

Remove unused terraform variables

---

images/paws-hub/Dockerfile
images/singleuser/Dockerfile
paws/Chart.yaml
paws/values.yaml
terraform/123_6.tf

Upgrade helm chart

---

paws/values.yaml

Grant admin users admin

---

images/singleuser/Dockerfile
paws/values.yaml

Bump jupyterlab version

---

terraform/123_5.tf
terraform/vars.tf

Increase worker node count

---

paws/values.yaml

Reduce memory request for single user

---

ansible/paws.yaml
paws/values.yaml

In case we need another cluster

---

.github/workflows/jobber.yaml
.github/workflows/minesweeper.yaml
.github/workflows/nbserve.yaml
.github/workflows/paws-hub.yaml
.github/workflows/renderer.yaml
.github/workflows/singleuser.yaml

Update to latest build-and-push

---

images/paws-hub/Dockerfile
paws/Chart.yaml
paws/values.yaml
terraform/123_8.tf

Update zero to jupyterhub chart

---

images/singleuser/Dockerfile
paws/values.yaml

Jupyterlab to 4.0.8

---

ansible/paws.yaml
terraform/123_9.tf

Update ingress-nginx to 4.8.3

---

paws/values.yaml

Hey @vivian-rook is the pr ready?

Remove variables if unused

---

images/singleuser/Dockerfile
paws/values.yaml

jupyterlab to 4.0.9

---

tofu/vars.tf

Update fcos version

---

tofu/123_11.tf

Upgrade fcos version

---

images/singleuser/Dockerfile
paws/values.yaml

Upgrade jupyterlab to 4.0.10

---

images/singleuser/Dockerfile
paws/Chart.yaml
paws/values.yaml
tofu/123_12.tf

Update paws helm chart

---

images/singleuser/Dockerfile
paws/values.yaml

Upgrade RStudio

---

ansible/paws.yaml
ansible/templates/prometheus-ingress.yaml.j2

Install kube-state-metrics

---

README.md
ansible/files/prometheus-data.sh
ansible/paws.yaml
deploy.sh

Restore prometheus

---

images/singleuser/Dockerfile
paws/values.yaml

Upgrade OpenRefine

---

images/singleuser/Dockerfile
paws/values.yaml

Jupyterlab to 4.1.1

---

ansible/paws.yaml

Increase prometheus retention

---

images/singleuser/install-extensions
paws/values.yaml

Remove nbextension

---

tofu/vars.tf

Increase node count for outreachy

---

tofu/vars.tf

Outreachy applicants are making paws popular
Bug: T359591

Increase worker nodes

---

images/singleuser/Dockerfile
paws/values.yaml

Upgrade jupyterlab to 4.1.4

---

tofu/vars.tf

Bump worker nodes

---

tofu/vars.tf

Remove unused variable

---

images/singleuser/install-julia
paws/values.yaml

Upgrade julia

---

images/singleuser/Dockerfile
paws/values.yaml

Use upstream jupyter-rsession-proxy

---

tofu/vars.tf

Reduce cluster size

---

images/singleuser/Dockerfile
paws/values.yaml

Upgrade jupyterlab to 4.1.8

---

images/singleuser/Dockerfile
paws/values.yaml

Test rollback of openrefine

---

ansible/paws.yaml

upgrade ingress-nginx

---

ansible/paws.yaml

Remedy timing bug

---

images/renderer/Dockerfile
paws/values.yaml

update to ubuntu 24.04

---

images/minesweeper/Dockerfile
paws/values.yaml

minesweeper image update

---

images/jobber/Dockerfile
paws/values.yaml

update to alpine 3.20.0

---

deploy.sh

Improve idempotency detection with helm diff

---

images/singleuser/Dockerfile
paws/values.yaml

upgrade juptyerlab

---

images/singleuser/Dockerfile
paws/values.yaml

Update open refine

---

ansible/paws.yaml

update prometheus chart

---

ansible/ansible.cfg

Remove warning on ansible inventory

---

.gitignore
ansible/ansible.cfg
deploy.sh

Remedy warning in collections install

---

images/paws-hub/Dockerfile
paws/Chart.yaml
paws/values.yaml
tofu/126a.tf

Update to chart version 3.3.8

---

deploy.sh

Upgrade ansible

---

.github/workflows/jobber.yaml
.github/workflows/minesweeper.yaml
.github/workflows/nbserve.yaml
.github/workflows/paws-hub.yaml
.github/workflows/renderer.yaml
.github/workflows/singleuser.yaml

Build and push update

---

images/singleuser/Dockerfile
paws/values.yaml

Update Wikimedia Commons Extension

---

ansible/paws.yaml

Upgrade ingress-nginx to v4.12.1
