toolforge/paws

singleuser/Dockerfile
singleuser/install-pwb
singleuser/user-config.py

- Install via a separate script to reduce number of Docker
Layers
- Do not install Pillow, since it requires a lot of packages

Install requirements and dev-requirements directly

---

singleuser/requirements.txt

When used within Pywikibot there seams to be no need to install it with `pip` but when using it as a standalone library I find myself installing it all the time.

Include mwparserfromhell by default

---

images/singleuser/Dockerfile

A new "stable" tag was introduced which indicates a stable release of
pywikibot whereas master branch is under perpetual development and may
fail in some circumstanced during developing. This tag is updated
monthly when the tests passed or ealier if necessary e.g. upstream
changes.
The more stable release should be used for PAWS.
Bug: T217908

Update pywikibot from last stable release

---

images/singleuser/Dockerfile
images/singleuser/hide_clusters_tab.css

See [T120629](https://phabricator.wikimedia.org/T120629) in Phabricator.
As @chicocvenancio said in the Phabricator task mentioned above, the CSS snippet written by @framawiki is simpler and more specific than the suggested in #22.

Hide clusters tab with CSS

---

paws/values.yaml

Current postStart hook gets to a depracated(?) `stable` tag in pywikibot.
The updated code is in the `stable` branch, using git pull should solve the
issues.
Bug T258142

Update pywikibot from stable branch

---

paws/production.yaml
paws/templates/db-proxy.yaml

Because the luaproxy interprets everything as the same IP (correctly),
the original version of the multiinstance changes won't work until they
are more than a bunch of records pointing to the same IP.
Rolling that back so that PAWS can still access the replicas until then.
Bug: T260389

emergency change: temporarily rolling back multiinstance proxy

---

images/nbserve/nginx.py

In some cases, notebooks can take a fair while for the renderer to
render. As is, the nbserve pod will just timeout and disconnect, causing
a 504.
Deployment of this in the current state will require manually building
the image, since we haven't re-established the deploy hook properly yet.
Bug: T270820

paws-public: increase the timeout for read at the nginx proxy

---

images/nbserve/nginx.py

Since the error I'm specifically trying to fix is something taking 150+
seconds to render, the read timeout should be fine. The connect timeout
might not be.
Bug: T270820

paws-public: expand the connect timeout on the nbserve process

---

images/nbserve/nginx.py

It seems we are missing the uwsgi timeout value to make the larger
values work. Additionally they may not apply everywhere we need in
specific location blocks.
Bug: T270820

nbserve timeouts: add timeout and hoist all of them to server block

---

paws/production.yaml
paws/templates/beta-db-proxy.yaml
paws/values.yaml

These two commits **should** create a parallel mysql-proxy that talks to the multi-instance wiki replicas. Please check it. helm renders it fine at very least in both dev mode and production.
I cannot actually test it except in the cluster since this is something that only lives in the cloud. As long as I've caught any possible name clashes, it should have no impact on the existing services, though.

Multiinstance mysql

---

images/singleuser/Dockerfile
images/singleuser/jupyter_notebook_config.py
images/singleuser/proxies/openrefine-logo.svg
images/singleuser/requirements.txt
images/singleuser/rsession.conf

Looks like OpenRefine is used in wikidata a bit
https://www.wikidata.org/wiki/Wikidata:Tools/OpenRefine,
so should be useful here
You can test this with:
`$ docker build -t paws images/singleuser`
`$ docker run -p 8888:8888 paws jupyter notebook --ip=0.0.0.0`
This should start a notebook server, and print a URL with a token
you can use to connect to the docker container & test the image.
Since this uses port forwarding, it'll most likely only work if you
are running docker locally (and not via docker-machine)
You can open RStudio by going to 'New -> OpenRefine'
Depends on #64, which depends on #62

Setup OpenRefine on PAWS

---

images/singleuser/Dockerfile

Over the last few years,
[nbgitpuller](https://jupyterhub.github.io/nbgitpuller/)
has become a very common way to distribute examples / learning materials
to participants in a workshop. This lets them start from a working base
but modify it as they want.
Once installed, you can create a specific link with
https://jupyterhub.github.io/nbgitpuller/link.html that points to
paws and to the git repo you want to 'pull'. If you use this link:
https://hub.paws.wmcloud.org/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fyuvipanda%2Frequirements&urlpath=tree%2Frequirements%2F&branch=master
it will pull in https://github.com/yuvipanda/requirements locally
and let you edit it. If someone changes the git repo, you can click it
again to pull in new changes.

Add nbgitpuller to PAWS

---

images/singleuser/Dockerfile

Allows users to build and share dashboards from
Jupyter notebooks. See https://github.com/voila-dashboards/voila
for more information.

Install voila for dashboards

---

images/singleuser/Dockerfile

Openrefine creates a workspace.json with cleartext secrets in
it that seems to just do whatever the umask says. Since PAWS is public
by default, that means the information is on the web.
This is actually already applied everywhere because the software also
changes the file back if you try to chmod it, meaning that it being
present is enough to keep opening your file to the internet.
Bug: T283839

remove openrefine pending security issue resolution

---

manifests/psp.yaml
paws/templates/public.yaml

PAWS public can be prevented from leaking more data by setting a UID
different from PAWS. It variously worked without doing this, but it
doesn't always. In order to give users the ability to manage data better
This setup will help.
Additionally, this is already applied. No deploy necessary.
This is just for public acknowledgement and comment.

update psps for paws public

---

images/singleuser/Dockerfile

This as of now, all files from openrefine will be private, which isn't
great, but that's better than making them all public, perhaps.
Let's try turning it back on, perhaps.
Bug: T283839

restore openrefine now that it is more private

---

images/singleuser/Dockerfile

I don't know why they were here, but I don't think they're helpful. It's
useful to be able to see the progress, and some CI systems will think
your build is stalled and time it out if you don't output anything.

Remove /dev/null pipes

---

images/singleuser/Dockerfile

In c77ca1f4a923c30 I missed that the base notebook packages were being
installed even earlier. The upgrade of pip/setuptools/wheel now happens
immediately after venv creation, so it'll be there for all dependencies
as originally intended.

Upgrade pip/setuptools/wheel right after venv creation

---

images/singleuser/Dockerfile

Installing the "stable" branch has the benefit of using the latest
release whenever the image is rebuilt. However, that means to get the
latest Pywikibot version, someone will need to do a no-change rebuild of
the image, bypassing Git and the standard CI/CD processes.
Specifying an explicit version means this will just work with docker
caching and cause a commit to go through CI/CD like all other changes.
It does mean that a new commit needs to be made for each new version.
LibUp will file a task in the #PAWS Phabricator project[1] every time a
new Pywikibot version is released so it doesn't get forgotten about.
I put the PYWIKIBOT_VERSION env at the top for easier readability, which
means bumping Pywikibot will invalidate the whole build cache. I'm not
sure if that's a good thing.
[1] …

Install a specific version of Pywikibot

---

images/nbserve/nginx.py
images/renderer/Dockerfile
images/renderer/renderer.py
paws/values.yaml

(minikube1.23 is now merged, shouldn't need to do any merge tricks for this now) To test this update I updated my hosts file with:
`minikube ip` public.paws.wmcloud.org
`minikube ip` paws.wmcloud.org
`minikube ip` hub.paws.wmcloud.org
At which point notebooks would appear as described in "Alter the URL manually" :
https://wikitech.wikimedia.org/wiki/PAWS/Getting_started_with_PAWS#Share

renderer to include md and rst files

---

images/singleuser/Dockerfile
images/singleuser/install-julia
paws/values.yaml

Bug: T282969
I could use some opinion on how the kernel.json file gets put in place. Not quite clear on how the others do it, they don't use a cp, though perhaps it is because they are more pip based that they know where to put the file as part of their install?

add Julia kernel

---

README.md

This adds instructions and link for changing `minikube` drivers to README.md as sometimes, on some machines this can solve the issue of `helm install` failing.

Add instructions about changing minikube drivers

---

.github/workflows/jobber.yaml
.github/workflows/nbserve.yaml
.github/workflows/paws-hub.yaml
.github/workflows/renderer.yaml
.github/workflows/singleuser.yaml
.github/workflows/update-container-tags.yaml

This change will enable a PR from a fork (rather than an internal branch) to run the workflows. In particular the PR will be able to build a container, and push it to quay (with the pr-<pr number>) tag. So long as the PR submitter enabled the "Allow edits and access to secrets by maintainers" this will also go and update their values.yaml with the docker tag that the pr built.
This does open the door to some injection possibilities:
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
First the scope that we are talking about is two creds, one the robot account personal access token used by the commit, and the second a robot account token with write access to the five quay.io registries that the workflows manage.
According to the above the access token should be …

Enable PRs from fork to build containers

---

images/singleuser/Dockerfile
paws/values.yaml

This reverts commit 4b7e9798690916310b2e04bc207034f2e70b9cb7.
If I'm understanding correctly this is necessary to unblock changes to the singleuser container. And will go back in as part of
https://github.com/toolforge/paws/pull/111

Revert "Bump openrefine to 3.5.0"

---

README.md

Updates to README to reflect newer ci.
removed:
NOTE: By default the mariadb chart keeps a PersistentVolumeClaim...
As I don't believe that is used now that we don't put a local mediawiki with the minikube install. If anyone knows this not to be true please correct me.

update to reflect updated ci

---

images/singleuser/requirements.txt
paws/values.yaml

wmpaws makes it simpler to run SQL queries against
replicas: compare `wmpaws.run_sql('...', 'cswiki')`
with a lot of boilerplate code in the currently recommmended way:
https://public.paws.wmcloud.org/User:JHernandez_(WMF)/Accessing%20Wikireplicas%20from%20PAWS.ipynb
Bug: T298189

images/singleuser: Add wmpaws to requirements

---

images/singleuser/requirements.txt
paws/values.yaml

Gets rstudio working in minikube.
Opening https://phabricator.wikimedia.org/T302164 to track the upgrading of jupyter-rsession-proxy

older jupyter-rsession-proxy to get rstudio working

---

images/singleuser/Dockerfile
paws/values.yaml

as current update to 3.4.0 fails to build on crypto
see:
https://phabricator.wikimedia.org/T307919
https://github.com/toolforge/paws/pull/145
for more information.

pin jupyterlab version

---

images/singleuser/Dockerfile
paws/values.yaml

In addition to getting this up to a newer jupyerhub version,
it also appears to fix an issue with jupyterlab-link-share,
where it was not sharing a token, thus was not working.
Bug: T308568

bump jupyterhub version

---

paws/values.yaml

New builds of renderer don't seem to work. Give internal
server error warning rather than renderering the page.
Opened T308975 to track.

Renderer giving server error

---

paws/production.yaml
paws/templates/public.yaml
paws/values.yaml

Sometimes the renderer gets pinned from requests.
Autoscaling should prevent it from getting overloaded.
Bug: T320776

autoscaling for renderer deployment

---

paws/values.yaml

Currently single user cpu request is about 50x the average request Lowering to better resemble typical usage. Limit remains the same As such heavy users should not be imnpacted.
Bug: T327204

lower single user cpu request

---

images/nbserve/Dockerfile
images/nbserve/robots.txt
paws/templates/nbserve/nginx.yaml
paws/values.yaml

To replace the robots.txt file someone added to the NFS root (which then
broke maintain-dbusers).
Untested, unfortunately.

nbserve: Serve a deny-all robots.txt file

---

images/singleuser/Dockerfile
paws/values.yaml

OpenRefine version bump

---

images/singleuser/requirements.txt
paws/values.yaml

https://phabricator.wikimedia.org/T342144

Pin PyYAML 6.0.1 to get around https://github.com/yaml/pyyaml/issues/601

---

images/singleuser/Dockerfile
paws/values.yaml

Install wikibase-cli

---

images/singleuser/requirements.txt
paws/values.yaml

No longer needed according to https://github.com/plotly/jupyter-dash
Bug: T358621

Remove jupyter-dash

---

images/paws-hub/Dockerfile
images/singleuser/Dockerfile
paws/Chart.yaml
paws/values.yaml
tofu/123_13.tf

Upgrade chart

---

README.md

Update minikube instructions

---

images/singleuser/Dockerfile
images/singleuser/r/Rprofile.site
images/singleuser/r/cran.list
images/singleuser/r/rsession.conf
images/singleuser/requirements.txt
paws/values.yaml

update to ubuntu 24.04

---

images/singleuser/install-extensions
paws/values.yaml

Bug: [T358604](https://phabricator.wikimedia.org/T358604)
Live installing the new labpawspublic version in a running server yields the expected links and menu items.

Upgrade labpawspublic

---

paws/values.yaml

I'm not sure what kind of network connections PAWS users need from their
notebooks, but I assume most will be HTTP/S connections to external
websites or APIs, or Git repositories served over HTTP/S.
Connections to UDP ports 53 (DNS) and 123 (NTP) are also legitimate.
Blocking other types of ports and protocols should prevent several forms
of malicious traffic that could originate from PAWS.
Bug: [T381373](https://phabricator.wikimedia.org/T381373)

Block non-HTTP connections to external IPs

---

images/singleuser/Dockerfile
paws/values.yaml

Upgrade openrefine

---

paws/values.yaml

The default is LoadBalancer, which creates an Octavia load balancer to expose the proxy. But we already expose the proxy via an Ingress, so we can set the proxy service to "type: ClusterIP".

Use ClusterIP for proxy service
